Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  ldapurl: "ldaps://ldap.csh.rit.edu"
  ldapdn: "uid=dgonyeo,ou=users,dc=csh,dc=rit,dc=edu"
  ldappassword: "lolpassword"
  smtpserver: "mail.csh.rit.edu"
  emailfrom: "dgonyeo@csh.rit.edu"
  emailuser: "dgonyeo"
  emailpassword: "lolpassword"

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  <<: *defaults
